### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by wkhaliddev1** [catalyst/moodle-webservice_restful#26]
The Restful plugin doesn't work with moodle versions greater than 4.1
Moodle tracker: [https://tracker.moodle.org/browse/CONTRIB-9559](url)

**Comment by golenkovm** [comment]
Hi @wkhaliddev1 

Thank you for reporting this. Please be advised that Moodle 4.2-4.4 compatible version of the plugin was pushed to the plugin directory yesterday, the 7th of May 2024 https://moodle.org/plugins/webservice_restful/versions . This was implemented as part of https://github.com/catalyst/moodle-webservice_restful/issues/22 and we got confirmations that the plugin works as expected. Could you please confirm that you are using the latest plugin version? Please refer to Moodle 4.2-4.4 plugin branch https://github.com/catalyst/moodle-webservice_restful/tree/MOODLE_402_STABLE . If you still face the issue please feel free to provide more details like testing scenarious, errors, traces, screenshots etc.

Kind regards,
Misha

**Comment by wkhaliddev1** [comment]
Hi @golenkovm 

Thank you for responding so quick on the issue. I tested the plugin on my end and its working perfectly fine. 
I was previously working on the old version of plugin **2022052500**
Just upgraded the plugin from Stable branch and its working as expected. 🚀
