### ISSUE TITLE
Exception: No Authorization header found in request sent to Moodle

### ISSUE THREAD

**Issue by rajineder** [catalyst/moodle-webservice_restful#3]
I am following [this tutorial](https://moodle.org/plugins/webservice_restful) and I have followed all steps to enable web services and also generate a valid token but when I tried to run API call it gave me following error 

{"exception":"moodle_exception","errorcode":"noauthheader","message":"No Authorization header found in request sent to Moodle"}

but I am sending a valid token in the header with other required information like below

curl -X POST \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H 'Authorization: 4838e6771cdbfd1eefbf37b3839587d9' \
-d'{"options": {"ids":[2]}}' \
"mydomain.com/webservice/restful/server.php/core_course_get_courses"

I have also tried a token like: {4838e6771cdbfd1eefbf37b3839587d9} but no luck
please help

**Comment by mattporritt** [comment]
Hi @rajineder 
Can you please let me know what version of Moodle and PHP you are using?
Also have you been able to make successful webservice calls using just core Moodle features?

Thanks

**Comment by rajineder** [comment]
Hi @mattporritt I have tried following Moodle versions
1. Moodle 3.5 
2. Moodle 3.4 
PHP version 7.0
I have tried Moodle core features to make API call and it's working and got all required data successfully.

**Comment by mattporritt** [comment]
Thanks for the info, I will do some testing and let you know.

**Comment by dancreatech** [comment]
@mattporritt @rajineder what was the solution for this? I am facing the same issue. Raised here #11

**Comment by dancreatech** [comment]
> @mattporritt @rajineder what was the solution for this? I am facing the same issue. Raised here #11

Never mind, used the version that @mattporritt mentioned and it was resolved. Cheers! Closing issue #11

**Comment by JosePaulo95** [comment]
I'm still facing this

**Comment by dancreatech** [comment]
> I'm still facing this

Hi @JosePaulo95, if you've downloaded the extension from the moodle plugin directory, it seems to have link to an older version. In the latest version this issue has been fixed. Please download the master branch of this repo in a zip and extract it to the restful folder on your server as I did (refer to the issue #11)

**Comment by santoshndev** [comment]
I am getting the same error whenever i sent request through postman.. any solution?

**Comment by nadavkav** [comment]
After migrating some Moodle instances to AWS, I started getting these error messages too :-(
I am using version 2018102100
I am using AWS CloudFront, and when playing with different header caching I manage to get different error messages.
But I could not resolve this, yet... (I am still digging into this)

**Comment by nadavkav** [comment]
With the help of @brendanheywood , I found out that I need to add the "Accept" HTTP Header to the CF behavior settings, which solved this issue for us.

More info:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-headers-behavior

Here is what we eventually use:
![image](https://user-images.githubusercontent.com/231168/160483651-b52ba2f0-a87e-4e23-b4cd-9ba717745863.png)

**Comment by brendanheywood** [comment]
@nadavkav did you end up doing any testing to confirm if that ended up reducing your cache hit rate and if so by what amount?

**Comment by nadavkav** [comment]
@brendanheywood , I am going to give it a week (of data) to see what change in caching it made.
All in all, the AWS CF does not cache much. only CSS, JS, and images.
So I am not sure how much effect I will from this.
But I will report as soon as I have some interesting data.
