### ISSUE TITLE
No Authorization Header???

### ISSUE THREAD

**Issue by MarioFuchs** [catalyst/moodle-webservice_restful#5]
We are getting an exception 

{"exception":"moodle_exception","errorcode":"noauthheader","message":"No Authorization header found in request sent to Moodle"}

with the following post. Also tried via Windows PowerShell, same message. Also tried another function.

curl -X POST 
-H "Content-Type: application/json" 
-H "Accept: application/json" 
-H 'Authorization: ca***HIDDEN***aa4' 
-d'options[ids][0]=6' 
"https://moodle.company.com/webservice/restful/server.php/core_course_get_courses"

Can anyone help please.
Mario

**Comment by mattporritt** [comment]
Hi Mario,
On your Moodle server, what are you using as your webserver, NGINX or Apache?

**Comment by MarioFuchs** [comment]
Sorry for closing, Wrong click.

**Comment by jim3ex** [comment]
What was the resolution to this? We are seeing the same problem. (MAMP, Apache)

**Comment by mattporritt** [comment]
Are yo using the latest code from this repository? It contains a fix for Apache as it passes the headers differently than Nginx

**Comment by jim3ex** [comment]
Hi Matt,

I’ll check tomorrow. Thanks!

Jim
