### ISSUE TITLE
dml_missing_record_exception Installing from master

### ISSUE THREAD

**Issue by rajp84** [catalyst/moodle-webservice_restful#6]
Installing the previos version, I get the "No Authorization header found in request" error message.

If i install the latest version from master, i get the following exception when trying to make a REST call:

`{"exception":"dml_missing_record_exception","errorcode":"invalidrecord","message":"Can not find data record in database table external_functions."}`

**Comment by martin-martin** [comment]
Sounds like these might be two different issues:

- `No Authorization header found in request`: you may have forgotten to provide your `wstoken` in the Authorization header
- `dml_missing_record_exception`: the resource you are trying to access may not exist in your database

Just my two cents, also trying to figure out why I'm getting the `dml_missing_record_exception` in a call at the moment, even though my resource seems to exist, but I might be not understanding the API all the way yet. Maybe it's helpful ¯\_(ツ)_/¯
