### ISSUE TITLE
Is this plugin support version 3.6.2 ?

### ISSUE THREAD

**Issue by NikoNar** [catalyst/moodle-webservice_restful#7]
Just want to know is this plugin support version 3.6.2 or higher?
It's installed successfully, but when I tried to make a call following the instructions it's all time returned me "No Authorization header found in request sent to Moodle" response.

**Comment by kisonay** [comment]
this typically has to due with your webserver configuration.

**Comment by mattporritt** [comment]
The plugin is not automatically tested against Mooole 3.6 as it is out of support. But it still should work as there aren't any major webservice changes in that version of Moodle.
No Authorization being passed, is typically due to the setup of your webserver (Apache or Nginx)
