### ISSUE TITLE
Trying to get the function core_user_create_users to work

### ISSUE THREAD

**Issue by rklingaman** [catalyst/moodle-webservice_restful#8]
I have a few other functions working but not this one and I'm sure its just because I can't get the parameters set correctly.

curl -X POST \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H 'Authorization: 4444' \
-d '{"users": {"[0][username]":"testusername","[0][password]":"testpassword","[0][firstname]":"testfirstname","[0][lastname]":"testlastname","[0][email]":"testemail@example.com","[0][idnumber]":"0000001"}}' \
"https://server.example.com/webservice/restful/server.php/core_user_create_users"

I've tried it a few different ways but I'm struggling with how to convert the existing API documentation to use it for this plugin.

**Comment by hikaru150s** [comment]
> I have a few other functions working but not this one and I'm sure its just because I can't get the parameters set correctly.
> 
> curl -X POST
> -H "Content-Type: application/json"
> -H "Accept: application/json"
> -H 'Authorization: 4444'
> -d '{"users": {"[0][username]":"testusername","[0][password]":"testpassword","[0][firstname]":"testfirstname","[0][lastname]":"testlastname","[0][email]":"[testemail@example.com](mailto:testemail@example.com)","[0][idnumber]":"0000001"}}'
> "https://server.example.com/webservice/restful/server.php/core_user_create_users"
> 
> I've tried it a few different ways but I'm struggling with how to convert the existing API documentation to use it for this plugin.

Have you try to change the body itself? I believe the ```[0]``` means an array index position, so the converted body seems like this.

```
{
	"users": [
		{
			"username": "testusername",
			"password": "testpassword",
			"firstname": "testfirstname",
			"lastname": "testlastname",
			"email": "testemail@example.com",
			"idnumber": "0000001"
		}
	]
}
```

I think your cURL code might be like this.
```
curl -X POST
-H "Content-Type: application/json"
-H "Accept: application/json"
-H 'Authorization: 4444'
-d '{"users":[{"username":"testusername","password":"testpassword","firstname":"testfirstname","lastname":"testlastname","email":"testemail@example.com","idnumber":"0000001"}]}'
```
